name: Jut-suTests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: "Выберите тип тестов для запуска";
          required: true
          default: "positive"
          type: choice
          options:
          - positive
          - negative
          - all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r ./requirements.txt
      - name: Set Pytest Marker
        id: set_marker
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "positive" ]; then
            echo "MARKER=positive" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.test_type }}" == "negative" ]; then
            echo "MARKER=negative" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.test_type }}" == "all" ]; then
            echo "MARKER=" >> $GITHUB_OUTPUT
          fi
      - name: Run UI-tests
        env:
          VALID_LOGIN: ${{secrets.VALID_LOGIN}}
          VALID_PASSWORD: ${{secrets.VALID_PASSWORD}}
        run: |
          # Конструируем команду pytest: 'pytest -m positive', 'pytest -m negative' или просто 'pytest'
          if [ -z "${{ steps.set_marker.outputs.MARKER }}" ]; then
            echo "Launching all tests..."
            pytest
          else
            echo "Launching tests with the marker: ${{ steps.set_marker.outputs.MARKER }}..."
            pytest -m "${{ steps.set_marker.outputs.MARKER }}"
          fi
