name: Jut-suTests

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Choose type of the tests'
        required: true
        default: 'positive'
        type: choice
        options:
          - positive
          - negative
          - all

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Run Selected UI-tests
        id: run_tests
        env:
          VALID_LOGIN: ${{secrets.VALID_LOGIN}}
          VALID_PASSWORD: ${{secrets.VALID_PASSWORD}}
          BASE_URL: ${{secrets.BASE_URL}}
          EXPECTED_PROFILE_TITLE:  ${{secrets.EXPECTED_PROFILE_TITLE}}
          EXPECTED_ERROR_MESSAGE: ${{secrets.EXPECTED_ERROR_MESSAGE}}
        run: |
          TESTS_TYPE="${{github.event.inputs.test_type}}"
          ALLURE_RESULTS_DIR=allure-results

          echo "ALLURE_REPORT_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          
          rm -rf $ALLURE_RESULTS_DIR
          mkdir -p $ALLURE_RESULTS_DIR

          echo "Starting tests for type: $TEST_TYPE"
          
          if [ "$TEST_TYPE" == "all" ]; then
            pytest --alluredir=$ALLURE_RESULTS_DIR
          elif [ "$TEST_TYPE" == "positive" ]; then
            pytest -m positive --alluredir=$ALLURE_RESULTS_DIR
          elif [ "$TEST_TYPE" == "negative" ]; then
            pytest -m negative --alluredir=$ALLURE_RESULTS_DIR
          else
            echo "Ivalid test type selected $TESTS_TYPE"
            exit 1
          fi

          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "::warning file=run_tests.sh,line=1::Pytest completed with failures (Exit code $exit_code)."
            # Продолжаем, чтобы сгенерировать отчет
          fi
          exit $exit_code
          
      - name: Build Allure Report
        if: always()
        uses: simple-actions/allure-report-action@v1.0.0
        with:
          allure_results_path: allure-results
          # gh-pages_branch: gh-pages

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ github.event.inputs.test_type }}
          path: allure-results
          
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-${{ github.event.inputs.test_type }}
          path: allure-report
        
      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_pages_token: ${{secrets.GH_PAGES_TOKEN}}
          publish_dir: allure-report
